pipeline {
    agent {
        label 'linux'
    }
    stages {
//        stage('Git') {
//            steps{
//                git branch: 'main', credentialsId: '98f5fbb9-b278-47f8-9dc4-16c426ecc1a7', url: 'git@github.com:SemenAmbarnov/vector-role.git'
//            }
//        }
        stage('Molecule install') {
            steps{
                sh 'pip install molecule==3.4.0'
                sh 'pip install "ansible-lint<6.0.0"'
                sh 'pip install molecule_docker'
            }
        }
        stage('Molecule test'){
            steps{
                sh 'molecule test -s centos7'
                cleanWs()
            }
        }
    }
}
